
export const Constants = {
  appname: 'AgentHi.Ai',
  continueToSignUp: 'Continue to sign up',
  weWillLogYouIn:`If you already have an account, we’ll log you in`,
  continueUsingMobile: 'Continue with Mobile',
  continueUsingEmail: 'Continue with Email',
  continueUsingGoole: 'Continue with Google',
  continueUsingGAuth2: 'Continue with G-Auth 2',
  byCreatingAccount: 'By creating account you are accepting the',
  byContinuing: 'By Continuing you agree to AgentHi.Ai',
  termAndConditions: 'Terms & Conditions',
  continue:'Continue',
  privacyPolicy: 'Privacy Policy',
  gladToSeeYou:'Glad to see you!',
  yourSubscriptionHasExpired:'Your subscription has expired',
  tapHereToRenew:'Tap here to renew',
  howICanHelp:`I'm here to help. How can I assist you today?`,
  aboutUs:'About us',
  save:'Save',
  about:'About',
  URLS:{
    YoutubePlaylist:'https://www.youtube.com/channel/UCkETvQOEJ6URFhV8inJTqNw',
    ContactUrl:'https://agenthi.ai/contact',
    AboutUs:'https://agenthi.ai/about-us'
  },
  myNotes:'My Notes',
  Notifications:'Notifications',
  UpdateAppointment:'Update Appointment',
  Notes:'Notes',
  SmartAssist:'Smart Assist',
  hello:'Hello ',
  twin:'Twin',
  twinHint:'(Twin is an AI assistant designed to help agents analyze smart notes, summarize content, perform intelligent searches, and assist with smart commands)',
  Optional:' (Optional)',
  aboutOptional:'(Optional but recommended to help clients understand you better)',
  dummyBio:`John is a skilled lawyer specializing in corporate law and civil litigation, known for strategic solutions, client-focused counsel, and over a decade of legal expertise.`,
  areYouSureWantToLogout:'Are you sure want to ',
  privacy:'Privacy',
  softwareVersion:'Version :',
  subscriptionDetails:'Subscription Details',
  contact:'Contact',
  howDoesItWorks:'How does it works?',
  howDoesItWorks_:'How It Works – Watch on YouTube',
  logout:'Logout',
  areYouSureWantToDelete:'delete?',
  yes:'Yes',
  no:'No',
  close:'Close',
  public:'Public',
  private:'Private',
  summary:'Summary',
  schedules:'Schedules',
  scheduledOn:`'s on`,
  pleaseSelectDate:'Please select a date to check ',
  noMeetingsAvailable:'Opps, looks like no meetings available',
  noReminderAvailable:'No Reminder available',
  noNotesAvailable:'Opps, looks like no notes available',
  noNotificationsAvailable:'No new notifications available',
  noNewClient:'No new client available',
  noLatestNoteAvailable:'No latest note available',
  noMatchingUserFound:'No matching client available',
  viewAll:'View all',
  add:'Add',
  messages:'Messages',
  LatesNotes:'Latest Notes',
  cancel:'Cancel',
  settings:'Settings',
  reminders: 'Reminder',
  and: ' and ',
  accept: 'Accept',
  accepted: 'Accepted',
  TermAndConditionUrl: 'https://agenthi.ai/termsofservice',
  PrivacyPolicyUrl: 'https://agenthi.ai/privacy',
  ByAppyouLabs:'By BitAdd Labs',

  Date: 'Date',
  Time: 'Time',
  Description: 'Description',
  SetReminder: 'Set reminder',
  AllFiedlsWarningMessage:'Please check the necessary fields',
  AppointmentCreated:'Appointment created and details shared with clients',
  ReminderCreated:'Reminder created',
  AppointmentDeleted:'Appointment deleted',
  ClientDeleted:'Client deleted',
  errorWhileCreatingAppoinment:'Error while creating Appointment',
  errorWhileDeletingAppoinment:'Error while deleting Appointment',
  errorWhileDeletingClient:'Error while deleting Client',
  errorWhileCreatingReminder:'Error while creating reminder',
  agentIdError:'An error occurred. Please try refreshing the page',
  clientCreationSuceessful:'Client profile successfully created',
  CreateReminder: 'Create a reminder',
  Title: 'Title',
  meetingTitle:'Meeting Title',
  noteHere:'Click here to add note',
  viewNotes:'View Notes',
  clickToviewNotes:'Click to view notes',
  searchClient:'Search Client',
  search:'Search',
  From: 'From',
  To: 'To',
  MeetingType: 'Meeting type',
  PersonToPerson: 'Person to Person',
  Online: 'Online',
  CreateNewMeeting: 'Create new meeting',
  CreateNewReminder: 'Create new reminder',
  createANew:'Create a new',
  client:'Client',
  Appointment:'Appointment',
  Reminder:'Reminder',
  CreateClient: 'Create \nClient',
  CreateAppointment: 'Create \nAppointment',
  CreateReminder_: 'Create \nReminder',
  other:'Other',
  editProfile:'Edit Profile',
  Editreminders:'Update Reminders',
  addClient:'Add Client',
  EditClient:'Edit Client Details',
  myProfile:'My Profile',
  firstName:'First name',
  displayName:'Display name',
  profileDetails:'Profile details',
  calenderDetails:'Calender details',
  QuickAction:'Quick Action',
  Calender:'My Calender',
  lastName:'Last name',
  AvailableDates:'Available dates',
  availability:'Availability',
  EachDayHours:'Each day hours',
  Exception:'Exception',
  mobileNo:'Mobile number',
  updateAvailability:'Update Availability',
  mobile:'Mobile Number       ',
  hoursPerDay:`Hour's per day`,
  countryCode:'Country code',
  email:'Email',
  occupation:'Occupation',
  attachments:'Attachments',
  Certificates:'Certificates',
  time_zone:'Timezone',
  supportedDocuments:'supported Documents',
  
  Secrets:{
    GoogleWebClientId:'532380161200-lbhb9ofkdbk8m513o0jvrcninsgi8ien.apps.googleusercontent.com',
    AndroidClientId:'1:532380161200:android:1607a15647684c24cdd775'
  },

  AgentBaseUrl:'http://44.210.108.191:3000/api/agents',
  ClientBaseUrl:'http://44.210.108.191:3000/api/clients',
  TwinBaseUrl:'http://44.210.108.191:3000/api/atwin',
  ApiBaseUrl:'http://44.210.108.191:3000/api/',
  AppointmentBaseUrl:'http://api.test.agenthi.ai:3000/api/appointments',
  ReminderBaseUrl:'http://api.test.agenthi.ai:3000/api/reminders',
  AndroidRedirectionUrlOauth:'com.agenthi.ai.android:/oauthredirect'
};
